# Custom Language File for Launcher Customizer

[ejs.app]
title = "AzurRP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@clentainne"
mediaDiscordURL = "https://discord.gg/rxcRYEBBUN"

[ejs.settings]
sourceGithubLink = "https://github.com/TheRayZens/AzurRP"
supportLink = "https://github.com/TheRayZens/AzurRP/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR AZURRP"
welcomeDescription = "Notre mission est de bâtir un univers roleplay contemporain, où la créativité collective de milliers de joueurs façonne une cité à la fois réaliste et surprenante. À travers une myriade de métiers inédits — de l’urbaniste digital à l’agent de sécurité privée, en passant par l’artiste multimédia, le bio-hacker ou le courtier en cryptomonnaies — chacun trouve sa place et son importance dans notre société virtuelle. Parcourez nos quartiers hyperconnectés, des gratte-ciels d’affaires aux souterrains clandestins, et appropriez-vous des systèmes novateurs de progression, d’économie et de justice. Embarquez pour une expérience immersive empreinte de sérieux et d’exigence, où chaque décision, chaque alliance ou trahison, façonne l’avenir de la cité. Mais attention : intégrité et persévérance seront vos meilleurs atouts pour vous hisser au sommet de ce monde en perpétuelle évolution."
welcomeDescCTA = "Vous n’êtes qu’à quelques clics de AzurRP."
